//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.GenerarReporteAsesorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="GenerarReporteAsesorWS.ReporteAsesorOpinionWS")]
    public interface ReporteAsesorOpinionWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ReporteAsesorOpinionWS/generarReporteAsesorRequest", ReplyAction="http://services/ReporteAsesorOpinionWS/generarReporteAsesorResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorResponse generarReporteAsesor(ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ReporteAsesorOpinionWS/generarReporteAsesorRequest", ReplyAction="http://services/ReporteAsesorOpinionWS/generarReporteAsesorResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorResponse> generarReporteAsesorAsync(ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteAsesor", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class generarReporteAsesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public generarReporteAsesorRequest() {
        }
        
        public generarReporteAsesorRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteAsesorResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class generarReporteAsesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteAsesorResponse() {
        }
        
        public generarReporteAsesorResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteAsesorOpinionWSChannel : ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteAsesorOpinionWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS>, ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS {
        
        public ReporteAsesorOpinionWSClient() {
        }
        
        public ReporteAsesorOpinionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteAsesorOpinionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteAsesorOpinionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteAsesorOpinionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorResponse ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS.generarReporteAsesor(ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest request) {
            return base.Channel.generarReporteAsesor(request);
        }
        
        public byte[] generarReporteAsesor(int arg0) {
            ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest inValue = new ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest();
            inValue.arg0 = arg0;
            ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorResponse retVal = ((ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS)(this)).generarReporteAsesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorResponse> ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS.generarReporteAsesorAsync(ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest request) {
            return base.Channel.generarReporteAsesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorResponse> generarReporteAsesorAsync(int arg0) {
            ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest inValue = new ProyectoOOIA.GenerarReporteAsesorWS.generarReporteAsesorRequest();
            inValue.arg0 = arg0;
            return ((ProyectoOOIA.GenerarReporteAsesorWS.ReporteAsesorOpinionWS)(this)).generarReporteAsesorAsync(inValue);
        }
    }
}
