//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.ReporteEventoAlumnoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="ReporteEventoAlumnoWS.ReporteEventoAlumnoWS")]
    public interface ReporteEventoAlumnoWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ReporteEventoAlumnoWS/generarReporteEventoRequest", ReplyAction="http://services/ReporteEventoAlumnoWS/generarReporteEventoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoResponse generarReporteEvento(ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/ReporteEventoAlumnoWS/generarReporteEventoRequest", ReplyAction="http://services/ReporteEventoAlumnoWS/generarReporteEventoResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoResponse> generarReporteEventoAsync(ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteEvento", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class generarReporteEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public generarReporteEventoRequest() {
        }
        
        public generarReporteEventoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteEventoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class generarReporteEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteEventoResponse() {
        }
        
        public generarReporteEventoResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteEventoAlumnoWSChannel : ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteEventoAlumnoWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS>, ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS {
        
        public ReporteEventoAlumnoWSClient() {
        }
        
        public ReporteEventoAlumnoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteEventoAlumnoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteEventoAlumnoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteEventoAlumnoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoResponse ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS.generarReporteEvento(ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest request) {
            return base.Channel.generarReporteEvento(request);
        }
        
        public byte[] generarReporteEvento(int arg0) {
            ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest inValue = new ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest();
            inValue.arg0 = arg0;
            ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoResponse retVal = ((ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS)(this)).generarReporteEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoResponse> ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS.generarReporteEventoAsync(ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest request) {
            return base.Channel.generarReporteEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoResponse> generarReporteEventoAsync(int arg0) {
            ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest inValue = new ProyectoOOIA.ReporteEventoAlumnoWS.generarReporteEventoRequest();
            inValue.arg0 = arg0;
            return ((ProyectoOOIA.ReporteEventoAlumnoWS.ReporteEventoAlumnoWS)(this)).generarReporteEventoAsync(inValue);
        }
    }
}
