//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.PonenteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", ConfigurationName="PonenteWS.PonenteWS")]
    public interface PonenteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/eliminarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/eliminarPonenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.PonenteWS.eliminarPonenteResponse eliminarPonente(ProyectoOOIA.PonenteWS.eliminarPonenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/eliminarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/eliminarPonenteResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.eliminarPonenteResponse> eliminarPonenteAsync(ProyectoOOIA.PonenteWS.eliminarPonenteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/insertarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/insertarPonenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.PonenteWS.insertarPonenteResponse insertarPonente(ProyectoOOIA.PonenteWS.insertarPonenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/insertarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/insertarPonenteResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.insertarPonenteResponse> insertarPonenteAsync(ProyectoOOIA.PonenteWS.insertarPonenteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/modificarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/modificarPonenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.PonenteWS.modificarPonenteResponse modificarPonente(ProyectoOOIA.PonenteWS.modificarPonenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/modificarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/modificarPonenteResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.modificarPonenteResponse> modificarPonenteAsync(ProyectoOOIA.PonenteWS.modificarPonenteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/listarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/listarPonenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.PonenteWS.listarPonenteResponse listarPonente(ProyectoOOIA.PonenteWS.listarPonenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/PonenteWS/listarPonenteRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/PonenteWS/listarPonenteResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.listarPonenteResponse> listarPonenteAsync(ProyectoOOIA.PonenteWS.listarPonenteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPonente", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPonenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_ponente;
        
        public eliminarPonenteRequest() {
        }
        
        public eliminarPonenteRequest(int id_ponente) {
            this.id_ponente = id_ponente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPonenteResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPonenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPonenteResponse() {
        }
        
        public eliminarPonenteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public partial class ponente : miembroExterno {
        
        private bool activoField;
        
        private int id_ponenteField;
        
        private string organizacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_ponente {
            get {
                return this.id_ponenteField;
            }
            set {
                this.id_ponenteField = value;
                this.RaisePropertyChanged("id_ponente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string organizacion {
            get {
                return this.organizacionField;
            }
            set {
                this.organizacionField = value;
                this.RaisePropertyChanged("organizacion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ponente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public abstract partial class miembroExterno : persona {
        
        private int id_miembro_externoField;
        
        private string ocupacionField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_miembro_externo {
            get {
                return this.id_miembro_externoField;
            }
            set {
                this.id_miembro_externoField = value;
                this.RaisePropertyChanged("id_miembro_externo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
                this.RaisePropertyChanged("ocupacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroExterno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ponente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fecha_nacimientoField;
        
        private bool fecha_nacimientoFieldSpecified;
        
        private int id_personaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
                this.RaisePropertyChanged("fecha_nacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_nacimientoSpecified {
            get {
                return this.fecha_nacimientoFieldSpecified;
            }
            set {
                this.fecha_nacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_nacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_persona {
            get {
                return this.id_personaField;
            }
            set {
                this.id_personaField = value;
                this.RaisePropertyChanged("id_persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPonente", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPonenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.PonenteWS.ponente invitado;
        
        public insertarPonenteRequest() {
        }
        
        public insertarPonenteRequest(ProyectoOOIA.PonenteWS.ponente invitado) {
            this.invitado = invitado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPonenteResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPonenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPonenteResponse() {
        }
        
        public insertarPonenteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPonente", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPonenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.PonenteWS.ponente invitado;
        
        public modificarPonenteRequest() {
        }
        
        public modificarPonenteRequest(ProyectoOOIA.PonenteWS.ponente invitado) {
            this.invitado = invitado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPonenteResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPonenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPonenteResponse() {
        }
        
        public modificarPonenteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPonente", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPonenteRequest {
        
        public listarPonenteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPonenteResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPonenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.PonenteWS.ponente[] @return;
        
        public listarPonenteResponse() {
        }
        
        public listarPonenteResponse(ProyectoOOIA.PonenteWS.ponente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PonenteWSChannel : ProyectoOOIA.PonenteWS.PonenteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PonenteWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.PonenteWS.PonenteWS>, ProyectoOOIA.PonenteWS.PonenteWS {
        
        public PonenteWSClient() {
        }
        
        public PonenteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PonenteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PonenteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PonenteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.PonenteWS.eliminarPonenteResponse ProyectoOOIA.PonenteWS.PonenteWS.eliminarPonente(ProyectoOOIA.PonenteWS.eliminarPonenteRequest request) {
            return base.Channel.eliminarPonente(request);
        }
        
        public int eliminarPonente(int id_ponente) {
            ProyectoOOIA.PonenteWS.eliminarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.eliminarPonenteRequest();
            inValue.id_ponente = id_ponente;
            ProyectoOOIA.PonenteWS.eliminarPonenteResponse retVal = ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).eliminarPonente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.eliminarPonenteResponse> ProyectoOOIA.PonenteWS.PonenteWS.eliminarPonenteAsync(ProyectoOOIA.PonenteWS.eliminarPonenteRequest request) {
            return base.Channel.eliminarPonenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.eliminarPonenteResponse> eliminarPonenteAsync(int id_ponente) {
            ProyectoOOIA.PonenteWS.eliminarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.eliminarPonenteRequest();
            inValue.id_ponente = id_ponente;
            return ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).eliminarPonenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.PonenteWS.insertarPonenteResponse ProyectoOOIA.PonenteWS.PonenteWS.insertarPonente(ProyectoOOIA.PonenteWS.insertarPonenteRequest request) {
            return base.Channel.insertarPonente(request);
        }
        
        public int insertarPonente(ProyectoOOIA.PonenteWS.ponente invitado) {
            ProyectoOOIA.PonenteWS.insertarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.insertarPonenteRequest();
            inValue.invitado = invitado;
            ProyectoOOIA.PonenteWS.insertarPonenteResponse retVal = ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).insertarPonente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.insertarPonenteResponse> ProyectoOOIA.PonenteWS.PonenteWS.insertarPonenteAsync(ProyectoOOIA.PonenteWS.insertarPonenteRequest request) {
            return base.Channel.insertarPonenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.insertarPonenteResponse> insertarPonenteAsync(ProyectoOOIA.PonenteWS.ponente invitado) {
            ProyectoOOIA.PonenteWS.insertarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.insertarPonenteRequest();
            inValue.invitado = invitado;
            return ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).insertarPonenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.PonenteWS.modificarPonenteResponse ProyectoOOIA.PonenteWS.PonenteWS.modificarPonente(ProyectoOOIA.PonenteWS.modificarPonenteRequest request) {
            return base.Channel.modificarPonente(request);
        }
        
        public int modificarPonente(ProyectoOOIA.PonenteWS.ponente invitado) {
            ProyectoOOIA.PonenteWS.modificarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.modificarPonenteRequest();
            inValue.invitado = invitado;
            ProyectoOOIA.PonenteWS.modificarPonenteResponse retVal = ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).modificarPonente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.modificarPonenteResponse> ProyectoOOIA.PonenteWS.PonenteWS.modificarPonenteAsync(ProyectoOOIA.PonenteWS.modificarPonenteRequest request) {
            return base.Channel.modificarPonenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.modificarPonenteResponse> modificarPonenteAsync(ProyectoOOIA.PonenteWS.ponente invitado) {
            ProyectoOOIA.PonenteWS.modificarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.modificarPonenteRequest();
            inValue.invitado = invitado;
            return ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).modificarPonenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.PonenteWS.listarPonenteResponse ProyectoOOIA.PonenteWS.PonenteWS.listarPonente(ProyectoOOIA.PonenteWS.listarPonenteRequest request) {
            return base.Channel.listarPonente(request);
        }
        
        public ProyectoOOIA.PonenteWS.ponente[] listarPonente() {
            ProyectoOOIA.PonenteWS.listarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.listarPonenteRequest();
            ProyectoOOIA.PonenteWS.listarPonenteResponse retVal = ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).listarPonente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.listarPonenteResponse> ProyectoOOIA.PonenteWS.PonenteWS.listarPonenteAsync(ProyectoOOIA.PonenteWS.listarPonenteRequest request) {
            return base.Channel.listarPonenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.PonenteWS.listarPonenteResponse> listarPonenteAsync() {
            ProyectoOOIA.PonenteWS.listarPonenteRequest inValue = new ProyectoOOIA.PonenteWS.listarPonenteRequest();
            return ((ProyectoOOIA.PonenteWS.PonenteWS)(this)).listarPonenteAsync(inValue);
        }
    }
}
