//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.CodigoAtencionWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", ConfigurationName="CodigoAtencionWS.CodigoAtencionWS")]
    public interface CodigoAtencionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/listarCodigoRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/listarCodigoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CodigoAtencionWS.listarCodigoResponse listarCodigo(ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/listarCodigoRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/listarCodigoResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.listarCodigoResponse> listarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/insertarCodigoRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/insertarCodigoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CodigoAtencionWS.insertarCodigoResponse insertarCodigo(ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/insertarCodigoRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/insertarCodigoResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.insertarCodigoResponse> insertarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/modificarCodigoRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/modificarCodigoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CodigoAtencionWS.modificarCodigoResponse modificarCodigo(ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/modificarCodigoRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CodigoAtencionWS/modificarCodigoResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.modificarCodigoResponse> modificarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public partial class codigoAtencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string codigoField;
        
        private string descripcionField;
        
        private int id_codigo_atencionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_codigo_atencion {
            get {
                return this.id_codigo_atencionField;
            }
            set {
                this.id_codigo_atencionField = value;
                this.RaisePropertyChanged("id_codigo_atencion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCodigo", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCodigoRequest {
        
        public listarCodigoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCodigoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CodigoAtencionWS.codigoAtencion[] @return;
        
        public listarCodigoResponse() {
        }
        
        public listarCodigoResponse(ProyectoOOIA.CodigoAtencionWS.codigoAtencion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCodigo", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo;
        
        public insertarCodigoRequest() {
        }
        
        public insertarCodigoRequest(ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCodigoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCodigoResponse() {
        }
        
        public insertarCodigoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCodigo", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo;
        
        public modificarCodigoRequest() {
        }
        
        public modificarCodigoRequest(ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCodigoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCodigoResponse() {
        }
        
        public modificarCodigoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CodigoAtencionWSChannel : ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodigoAtencionWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS>, ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS {
        
        public CodigoAtencionWSClient() {
        }
        
        public CodigoAtencionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodigoAtencionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodigoAtencionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodigoAtencionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CodigoAtencionWS.listarCodigoResponse ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS.listarCodigo(ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest request) {
            return base.Channel.listarCodigo(request);
        }
        
        public ProyectoOOIA.CodigoAtencionWS.codigoAtencion[] listarCodigo() {
            ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest inValue = new ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest();
            ProyectoOOIA.CodigoAtencionWS.listarCodigoResponse retVal = ((ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS)(this)).listarCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.listarCodigoResponse> ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS.listarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest request) {
            return base.Channel.listarCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.listarCodigoResponse> listarCodigoAsync() {
            ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest inValue = new ProyectoOOIA.CodigoAtencionWS.listarCodigoRequest();
            return ((ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS)(this)).listarCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CodigoAtencionWS.insertarCodigoResponse ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS.insertarCodigo(ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest request) {
            return base.Channel.insertarCodigo(request);
        }
        
        public int insertarCodigo(ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo) {
            ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest inValue = new ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest();
            inValue.codigo = codigo;
            ProyectoOOIA.CodigoAtencionWS.insertarCodigoResponse retVal = ((ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS)(this)).insertarCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.insertarCodigoResponse> ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS.insertarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest request) {
            return base.Channel.insertarCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.insertarCodigoResponse> insertarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo) {
            ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest inValue = new ProyectoOOIA.CodigoAtencionWS.insertarCodigoRequest();
            inValue.codigo = codigo;
            return ((ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS)(this)).insertarCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CodigoAtencionWS.modificarCodigoResponse ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS.modificarCodigo(ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest request) {
            return base.Channel.modificarCodigo(request);
        }
        
        public int modificarCodigo(ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo) {
            ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest inValue = new ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest();
            inValue.codigo = codigo;
            ProyectoOOIA.CodigoAtencionWS.modificarCodigoResponse retVal = ((ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS)(this)).modificarCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.modificarCodigoResponse> ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS.modificarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest request) {
            return base.Channel.modificarCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CodigoAtencionWS.modificarCodigoResponse> modificarCodigoAsync(ProyectoOOIA.CodigoAtencionWS.codigoAtencion codigo) {
            ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest inValue = new ProyectoOOIA.CodigoAtencionWS.modificarCodigoRequest();
            inValue.codigo = codigo;
            return ((ProyectoOOIA.CodigoAtencionWS.CodigoAtencionWS)(this)).modificarCodigoAsync(inValue);
        }
    }
}
