//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.CoordinadorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", ConfigurationName="CoordinadorWS.CoordinadorWS")]
    public interface CoordinadorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/eliminarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/eliminarCoordinadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorWS.eliminarCoordinadorResponse eliminarCoordinador(ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/eliminarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/eliminarCoordinadorResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.eliminarCoordinadorResponse> eliminarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/modificarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/modificarCoordinadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorWS.modificarCoordinadorResponse modificarCoordinador(ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/modificarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/modificarCoordinadorResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.modificarCoordinadorResponse> modificarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/insertarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/insertarCoordinadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorWS.insertarCoordinadorResponse insertarCoordinador(ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/insertarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/insertarCoordinadorResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.insertarCoordinadorResponse> insertarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/listarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/listarCoordinadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorWS.listarCoordinadorResponse listarCoordinador(ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorWS/listarCoordinadorRequest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorWS/listarCoordinadorResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.listarCoordinadorResponse> listarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCoordinador", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCoordinadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_coordinador;
        
        public eliminarCoordinadorRequest() {
        }
        
        public eliminarCoordinadorRequest(int id_coordinador) {
            this.id_coordinador = id_coordinador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCoordinadorResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCoordinadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCoordinadorResponse() {
        }
        
        public eliminarCoordinadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public partial class coordinador : miembroPUCP {
        
        private bool activoField;
        
        private int id_coordinadorField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_coordinador {
            get {
                return this.id_coordinadorField;
            }
            set {
                this.id_coordinadorField = value;
                this.RaisePropertyChanged("id_coordinador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coordinador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public abstract partial class miembroPUCP : persona {
        
        private System.DateTime fecha_inclusionField;
        
        private bool fecha_inclusionFieldSpecified;
        
        private int id_miembro_pucpField;
        
        private byte[] imagenDePerfilField;
        
        private string passwordField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha_inclusion {
            get {
                return this.fecha_inclusionField;
            }
            set {
                this.fecha_inclusionField = value;
                this.RaisePropertyChanged("fecha_inclusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_inclusionSpecified {
            get {
                return this.fecha_inclusionFieldSpecified;
            }
            set {
                this.fecha_inclusionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_inclusionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_miembro_pucp {
            get {
                return this.id_miembro_pucpField;
            }
            set {
                this.id_miembro_pucpField = value;
                this.RaisePropertyChanged("id_miembro_pucp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] imagenDePerfil {
            get {
                return this.imagenDePerfilField;
            }
            set {
                this.imagenDePerfilField = value;
                this.RaisePropertyChanged("imagenDePerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroPUCP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coordinador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fecha_nacimientoField;
        
        private bool fecha_nacimientoFieldSpecified;
        
        private int id_personaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
                this.RaisePropertyChanged("fecha_nacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_nacimientoSpecified {
            get {
                return this.fecha_nacimientoFieldSpecified;
            }
            set {
                this.fecha_nacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_nacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_persona {
            get {
                return this.id_personaField;
            }
            set {
                this.id_personaField = value;
                this.RaisePropertyChanged("id_persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCoordinador", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCoordinadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorWS.coordinador coordinador;
        
        public modificarCoordinadorRequest() {
        }
        
        public modificarCoordinadorRequest(ProyectoOOIA.CoordinadorWS.coordinador coordinador) {
            this.coordinador = coordinador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCoordinadorResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCoordinadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCoordinadorResponse() {
        }
        
        public modificarCoordinadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCoordinador", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCoordinadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorWS.coordinador coordinador;
        
        public insertarCoordinadorRequest() {
        }
        
        public insertarCoordinadorRequest(ProyectoOOIA.CoordinadorWS.coordinador coordinador) {
            this.coordinador = coordinador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCoordinadorResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCoordinadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCoordinadorResponse() {
        }
        
        public insertarCoordinadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCoordinador", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCoordinadorRequest {
        
        public listarCoordinadorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCoordinadorResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCoordinadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorWS.coordinador[] @return;
        
        public listarCoordinadorResponse() {
        }
        
        public listarCoordinadorResponse(ProyectoOOIA.CoordinadorWS.coordinador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoordinadorWSChannel : ProyectoOOIA.CoordinadorWS.CoordinadorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoordinadorWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.CoordinadorWS.CoordinadorWS>, ProyectoOOIA.CoordinadorWS.CoordinadorWS {
        
        public CoordinadorWSClient() {
        }
        
        public CoordinadorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoordinadorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinadorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorWS.eliminarCoordinadorResponse ProyectoOOIA.CoordinadorWS.CoordinadorWS.eliminarCoordinador(ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest request) {
            return base.Channel.eliminarCoordinador(request);
        }
        
        public int eliminarCoordinador(int id_coordinador) {
            ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest();
            inValue.id_coordinador = id_coordinador;
            ProyectoOOIA.CoordinadorWS.eliminarCoordinadorResponse retVal = ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).eliminarCoordinador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.eliminarCoordinadorResponse> ProyectoOOIA.CoordinadorWS.CoordinadorWS.eliminarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest request) {
            return base.Channel.eliminarCoordinadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.eliminarCoordinadorResponse> eliminarCoordinadorAsync(int id_coordinador) {
            ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.eliminarCoordinadorRequest();
            inValue.id_coordinador = id_coordinador;
            return ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).eliminarCoordinadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorWS.modificarCoordinadorResponse ProyectoOOIA.CoordinadorWS.CoordinadorWS.modificarCoordinador(ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest request) {
            return base.Channel.modificarCoordinador(request);
        }
        
        public int modificarCoordinador(ProyectoOOIA.CoordinadorWS.coordinador coordinador) {
            ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest();
            inValue.coordinador = coordinador;
            ProyectoOOIA.CoordinadorWS.modificarCoordinadorResponse retVal = ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).modificarCoordinador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.modificarCoordinadorResponse> ProyectoOOIA.CoordinadorWS.CoordinadorWS.modificarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest request) {
            return base.Channel.modificarCoordinadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.modificarCoordinadorResponse> modificarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.coordinador coordinador) {
            ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.modificarCoordinadorRequest();
            inValue.coordinador = coordinador;
            return ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).modificarCoordinadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorWS.insertarCoordinadorResponse ProyectoOOIA.CoordinadorWS.CoordinadorWS.insertarCoordinador(ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest request) {
            return base.Channel.insertarCoordinador(request);
        }
        
        public int insertarCoordinador(ProyectoOOIA.CoordinadorWS.coordinador coordinador) {
            ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest();
            inValue.coordinador = coordinador;
            ProyectoOOIA.CoordinadorWS.insertarCoordinadorResponse retVal = ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).insertarCoordinador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.insertarCoordinadorResponse> ProyectoOOIA.CoordinadorWS.CoordinadorWS.insertarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest request) {
            return base.Channel.insertarCoordinadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.insertarCoordinadorResponse> insertarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.coordinador coordinador) {
            ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.insertarCoordinadorRequest();
            inValue.coordinador = coordinador;
            return ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).insertarCoordinadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorWS.listarCoordinadorResponse ProyectoOOIA.CoordinadorWS.CoordinadorWS.listarCoordinador(ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest request) {
            return base.Channel.listarCoordinador(request);
        }
        
        public ProyectoOOIA.CoordinadorWS.coordinador[] listarCoordinador() {
            ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest();
            ProyectoOOIA.CoordinadorWS.listarCoordinadorResponse retVal = ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).listarCoordinador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.listarCoordinadorResponse> ProyectoOOIA.CoordinadorWS.CoordinadorWS.listarCoordinadorAsync(ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest request) {
            return base.Channel.listarCoordinadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorWS.listarCoordinadorResponse> listarCoordinadorAsync() {
            ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest inValue = new ProyectoOOIA.CoordinadorWS.listarCoordinadorRequest();
            return ((ProyectoOOIA.CoordinadorWS.CoordinadorWS)(this)).listarCoordinadorAsync(inValue);
        }
    }
}
