//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.ObtenerPlantillaCSVcargaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS")]
    public interface PlantillasCSVcargaWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services/PlantillasCSVcargaWS/obtenerPlantillaCSVRequest", ReplyAction="http://services/PlantillasCSVcargaWS/obtenerPlantillaCSVResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVResponse obtenerPlantillaCSV(ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/PlantillasCSVcargaWS/obtenerPlantillaCSVRequest", ReplyAction="http://services/PlantillasCSVcargaWS/obtenerPlantillaCSVResponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVResponse> obtenerPlantillaCSVAsync(ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPlantillaCSV", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class obtenerPlantillaCSVRequest {
        
        public obtenerPlantillaCSVRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPlantillaCSVResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class obtenerPlantillaCSVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public obtenerPlantillaCSVResponse() {
        }
        
        public obtenerPlantillaCSVResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlantillasCSVcargaWSChannel : ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlantillasCSVcargaWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS>, ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS {
        
        public PlantillasCSVcargaWSClient() {
        }
        
        public PlantillasCSVcargaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlantillasCSVcargaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantillasCSVcargaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantillasCSVcargaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVResponse ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS.obtenerPlantillaCSV(ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest request) {
            return base.Channel.obtenerPlantillaCSV(request);
        }
        
        public byte[] obtenerPlantillaCSV() {
            ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest inValue = new ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest();
            ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVResponse retVal = ((ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS)(this)).obtenerPlantillaCSV(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVResponse> ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS.obtenerPlantillaCSVAsync(ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest request) {
            return base.Channel.obtenerPlantillaCSVAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVResponse> obtenerPlantillaCSVAsync() {
            ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest inValue = new ProyectoOOIA.ObtenerPlantillaCSVcargaWS.obtenerPlantillaCSVRequest();
            return ((ProyectoOOIA.ObtenerPlantillaCSVcargaWS.PlantillasCSVcargaWS)(this)).obtenerPlantillaCSVAsync(inValue);
        }
    }
}
